kind: ConfigMap
apiVersion: v1
metadata:
  name: config-map-delete-controller
data:
    PORT: "8080"
    ASPNETCORE_ENVIRONMENT: Production
    MassTransit__QueueName: Delete
    MassTransit__Server: rabbitmq-sv
    MassTransit__User: guest
    MassTransit__Password: guest
