kind: ConfigMap
apiVersion: v1
metadata:
  name: config-map-creation-controller
data:
    PORT: "8080"
    ASPNETCORE_ENVIRONMENT: Production
    ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=TechChallenge;User ID=sa;Password=1q2w3e4r@#$;Trusted_Connection=False; TrustServerCertificate=True;"
    MassTransit__QueueName: Creation
    MassTransit__Server: rabbitmq-sv
    MassTransit__User: guest
    MassTransit__Password: guest
